#include "InputCapture.h"

void Input_Capture_Init() {
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOEEN;
	GPIOE->MODER &= ~(GPIO_MODER_MODE13 | GPIO_MODER_MODE14);
	GPIOE->MODER |= (GPIO_MODER_MODE13_1 | GPIO_MODER_MODE14_1);
	GPIOE->AFR[1] &= ~(GPIO_AFRH_AFSEL13 | GPIO_AFRH_AFSEL14);
	GPIOE->AFR[1] |= (GPIO_AFRH_AFSEL13_0 | GPIO_AFRH_AFSEL14_0);
	GPIOE->PUPDR &= ~(GPIO_PUPDR_PUPD13 | GPIO_PUPDR_PUPD14);
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	TIM1->PSC &= ~0xFFFF;
	TIM1->PSC |= 0x4F;
	TIM1->CR1 |= TIM_CR1_ARPE;
	TIM1->ARR |= 0xFFFF;
	TIM1->CCMR2 &= ~(TIM_CCMR2_CC3S | TIM_CCMR2_CC4S);
	TIM1->CCMR2 |= (TIM_CCMR2_CC3S_0 | TIM_CCMR2_CC4S_0 | TIM_CCMR2_IC3F | TIM_CCMR2_IC4F);
	TIM1->CCER &= ~(TIM_CCER_CC3NP | TIM_CCER_CC3P | TIM_CCER_CC4NP | TIM_CCER_CC4P);
	TIM1->CCER |= (TIM_CCER_CC3E | TIM_CCER_CC4E);
	TIM1->DIER |= (TIM_DIER_CC3DE | TIM_DIER_CC4DE | TIM_DIER_CC3IE | TIM_DIER_CC4IE | TIM_DIER_UIE);
	TIM1->EGR |= TIM_EGR_UG;
	TIM1->SR &= ~TIM_SR_UIF;
	TIM1->CR1 &= ~TIM_CR1_DIR;
	TIM1->CR1 |= TIM_CR1_CEN;
	NVIC_EnableIRQ(TIM1_UP_TIM16_IRQn);
	NVIC_SetPriority(TIM1_UP_TIM16_IRQn, 0);
	NVIC_EnableIRQ(TIM1_CC_IRQn);
	NVIC_SetPriority(TIM1_CC_IRQn, 1);
}
