#include "PWM.h"

void PWM_Init() {
	// Enable GPIO Port E Clock
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOEEN;
	
	// Enable TIM1 Clock
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	
	// Configure PE8
	GPIOE->MODER &= ~GPIO_MODER_MODE8;
	GPIOE->MODER |= GPIO_MODER_MODE8_1;
	GPIOE->OSPEEDR |= GPIO_OSPEEDR_OSPEED8;
	GPIOE->PUPDR &= ~GPIO_PUPDR_PUPD8;
	GPIOE->AFR[1] &= ~GPIO_AFRH_AFSEL8;
	GPIOE->AFR[1] |= GPIO_AFRH_AFSEL8_0;
	
	// Configure PWM Output for TIM1 CH 1N
	TIM1->CR1 &= ~TIM_CR1_DIR;
	TIM1->PSC |= 3UL;
	TIM1->ARR |= 0x270F;
	TIM1->CCMR1 &= ~TIM_CCMR1_OC1M;
	TIM1->CCMR1 |= TIM_CCMR1_OC1M_2;
	TIM1->CCMR1 |= TIM_CCMR1_OC1M_1;
	TIM1->CCMR1 |= TIM_CCMR1_OC1PE;
	TIM1->CCER &= ~TIM_CCER_CC1NP;
	TIM1->CCER |= TIM_CCER_CC1NE;
	TIM1->BDTR |= TIM_BDTR_MOE;
	TIM1->CCR1 |= 0x1388;
	TIM1->CR1 |= TIM_CR1_CEN;
}
